FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o updater ./cmd/updater

FROM alpine:latest

RUN apk --no-cache add ca-certificates git docker-cli docker-cli-compose

WORKDIR /app
COPY --from=builder /app/updater ./

CMD ["./updater"]
