#!/usr/bin/env python3
"""Seed a realistic running-tire-shop dataset through the live API.

Run AFTER reset_demo_data.sql has wiped the database. Everything is created
through the real HTTP API so every ledger invariant (FIFO batches, stock
movements, reservations, paid amounts) is maintained by the actual business
logic. Because the API stamps "now" on everything, the script also emits a
backdate SQL file that shifts timestamps to spread ~90 days of history;
apply it with psql immediately after this script finishes.

Usage:
    python3 seed_realistic.py [backdate-output.sql]
"""
import json
import random
import sys
import urllib.request
from datetime import date, timedelta

BASE = "http://localhost:8080/api/v1"
RATE = 4100  # KHR per USD, matches the branch setting
random.seed(42)
TODAY = date.today()

BACKDATE_SQL = [
    "-- Generated by seed_realistic.py — shifts API-created timestamps into the past.",
    "BEGIN;",
]


def api(method, path, body=None, token=None):
    req = urllib.request.Request(BASE + path, method=method)
    req.add_header("Content-Type", "application/json")
    if token:
        req.add_header("Authorization", "Bearer " + token)
    data = json.dumps(body).encode() if body is not None else None
    try:
        with urllib.request.urlopen(req, data=data) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        detail = e.read().decode()
        raise RuntimeError(f"{method} {path} -> {e.code}: {detail}\nbody: {body}") from None


def ts(days_ago, hour=None, minute=None):
    """A Phnom Penh business-hours timestamp literal N days in the past."""
    d = TODAY - timedelta(days=days_ago)
    h = hour if hour is not None else random.randint(8, 16)
    m = minute if minute is not None else random.randint(0, 59)
    return f"{d.isoformat()} {h:02d}:{m:02d}:{random.randint(0, 59):02d}+07"


def bd(sql):
    BACKDATE_SQL.append(sql + ";")


def backdate_invoice(inv_id, t):
    bd(f"UPDATE invoices SET issued_at='{t}', created_at='{t}', updated_at='{t}' WHERE id={inv_id}")
    bd(f"UPDATE payments SET created_at='{t}' WHERE invoice_id={inv_id}")
    bd(f"UPDATE stock_movements SET created_at='{t}' WHERE reference_type='invoice' AND reference_id={inv_id}")
    bd(f"UPDATE audit_logs SET created_at='{t}' WHERE entity_type='invoice' AND entity_id={inv_id}")


def backdate_job(job_id, t_created, t_completed):
    bd(f"UPDATE service_jobs SET created_at='{t_created}', started_at='{t_created}', "
       f"completed_at='{t_completed}', updated_at='{t_completed}' WHERE id={job_id}")


def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else "backdate_seed.sql"
    token = api("POST", "/auth/login", {"username": "admin", "password": "admin123"})["access_token"]
    print("logged in")

    # ------------------------------------------------------------------ suppliers
    suppliers = {}
    for name, phone, addr in [
        ("Sokha Tire Import & Trading", "023 883 456", "St. 271, Toul Kork, Phnom Penh"),
        ("Golden Wheel Trading Co.", "012 556 789", "Russian Blvd, Phnom Penh"),
        ("Mekong Auto Parts Co., Ltd.", "023 991 234", "St. 105, Chamkarmon, Phnom Penh"),
        ("CamboLub Distribution", "010 778 899", "National Road 4, Por Sen Chey"),
    ]:
        r = api("POST", "/suppliers", {"name": name, "phone": phone, "address": addr}, token)
        suppliers[name] = r["data"]["id"]
    print(f"suppliers: {len(suppliers)}")

    # ------------------------------------------------------------------ employees
    techs = []
    for name, pos, pay, base, comm, hired in [
        ("Sreyneang Pich", "Cashier", "salary", 280, 0, "2024-03-01"),
        ("Dara Sok", "Senior Technician", "hybrid", 250, 8, "2022-06-15"),
        ("Vibol Chea", "Technician", "hybrid", 220, 8, "2023-09-01"),
        ("Rithy Meas", "Junior Technician", "salary", 180, 0, "2025-11-10"),
    ]:
        r = api("POST", "/employees", {
            "name": name, "position": pos, "pay_type": pay,
            "base_salary": base, "commission_rate": comm, "hire_date": hired,
            "phone": f"0{random.randint(10, 99)} {random.randint(200, 999)} {random.randint(100, 999)}",
        }, token)
        if "Technician" in pos:
            techs.append(r["data"]["id"])
        elif pos == "Cashier":
            api("POST", f"/employees/{r['data']['id']}/create-account", {
                "username": "sreyneang", "password": "cashier123", "role": "staff",
                "permissions": ["invoice:view", "invoice:create", "invoice:update",
                                "customer:view", "customer:create", "customer:update",
                                "inventory:view", "service:view", "service:create", "service:update"],
            }, token)
    print(f"employees: 4 (techs: {techs})")

    # ------------------------------------------------------------------ products
    # (sku, name, buy, sell, opening, alert, size, brand, model, tire_type, category)
    tires = [
        ("TIRE-KEN-1656513", "Kenda Komet Plus 165/65R13", 22, 33, 6, 4, "165/65R13", "Kenda", "Komet Plus", "passenger"),
        ("TIRE-MAX-1756514", "Maxxis MA-307 175/65R14", 26, 38, 28, 4, "175/65R14", "Maxxis", "MA-307", "passenger"),
        ("TIRE-KEN-1856515", "Kenda KR23 185/65R15", 29, 42, 32, 4, "185/65R15", "Kenda", "KR23", "passenger"),
        ("TIRE-MIC-1856515", "Michelin Energy XM2+ 185/65R15", 54, 74, 18, 4, "185/65R15", "Michelin", "Energy XM2+", "passenger"),
        ("TIRE-WES-1956515", "Westlake RP18 195/65R15", 31, 45, 36, 4, "195/65R15", "Westlake", "RP18", "passenger"),
        ("TIRE-BRI-1956515", "Bridgestone Turanza T005A 195/65R15", 57, 79, 20, 4, "195/65R15", "Bridgestone", "Turanza T005A", "passenger"),
        ("TIRE-GOO-2055516", "Goodyear Assurance TripleMax 205/55R16", 61, 85, 14, 4, "205/55R16", "Goodyear", "Assurance TripleMax", "passenger"),
        ("TIRE-DUN-2056515", "Dunlop SP Sport LM705 205/65R15", 52, 72, 14, 4, "205/65R15", "Dunlop", "SP Sport LM705", "passenger"),
        ("TIRE-HAN-2156016", "Hankook Kinergy EX 215/60R16", 55, 78, 26, 4, "215/60R16", "Hankook", "Kinergy EX", "passenger"),
        ("TIRE-MIC-2156016", "Michelin Primacy 4 215/60R16", 82, 109, 20, 4, "215/60R16", "Michelin", "Primacy 4", "passenger"),
        ("TIRE-YOK-2155517", "Yokohama BluEarth-GT 215/55R17", 67, 94, 12, 4, "215/55R17", "Yokohama", "BluEarth-GT", "passenger"),
        ("TIRE-MAX-2256517", "Maxxis Bravo HP-M3 225/65R17", 57, 81, 26, 4, "225/65R17", "Maxxis", "Bravo HP-M3", "suv"),
        ("TIRE-MIC-2256517", "Michelin Primacy SUV+ 225/65R17", 94, 126, 14, 4, "225/65R17", "Michelin", "Primacy SUV+", "suv"),
        ("TIRE-DUN-2356018", "Dunlop Grandtrek PT3 235/60R18", 97, 131, 18, 4, "235/60R18", "Dunlop", "Grandtrek PT3", "suv"),
        ("TIRE-CON-2355518", "Continental UltraContact UC6 SUV 235/55R18", 104, 139, 6, 4, "235/55R18", "Continental", "UltraContact UC6", "suv"),
        ("TIRE-BRI-2656517", "Bridgestone Dueler A/T 693 265/65R17", 109, 144, 22, 4, "265/65R17", "Bridgestone", "Dueler A/T 693", "truck"),
        ("TIRE-MAX-2656517", "Maxxis AT-700 265/65R17", 84, 113, 18, 4, "265/65R17", "Maxxis", "AT-700", "truck"),
        ("TIRE-DUN-2656018", "Dunlop Grandtrek AT25 265/60R18", 124, 163, 14, 4, "265/60R18", "Dunlop", "Grandtrek AT25", "truck"),
        ("TIRE-TOY-2856018", "Toyo Open Country U/T 285/60R18", 148, 192, 8, 4, "285/60R18", "Toyo", "Open Country U/T", "truck"),
        ("TIRE-MIC-2454518", "Michelin Pilot Sport 4 245/45R18", 129, 172, 8, 4, "245/45R18", "Michelin", "Pilot Sport 4", "passenger"),
    ]
    parts = [
        ("PART-BAT-NS60L", "Battery NS60L GS Astra", 46, 66, 14, 3, "Battery"),
        ("PART-BAT-N70", "Battery N70 GS", 74, 103, 8, 2, "Battery"),
        ("PART-BRK-CAMRY", "Brake Pads Front Camry (ACV40)", 27, 44, 16, 4, "Brakes"),
        ("PART-BRK-CRV", "Brake Pads Front CR-V", 29, 47, 12, 3, "Brakes"),
        ("PART-FIL-TOY", "Oil Filter Toyota 90915-YZZE1", 3.2, 6, 60, 10, "Filters"),
        ("PART-FIL-HON", "Oil Filter Honda 15400-RTA", 3.4, 6.5, 40, 8, "Filters"),
        ("PART-AIR-CAMRY", "Air Filter Camry", 6, 11, 20, 5, "Filters"),
        ("PART-WIP-2418", "Wiper Blade Set 24\"/18\"", 7.5, 14, 28, 5, "Accessories"),
        ("PART-SPK-IRID", "Spark Plug Iridium (set of 4)", 23, 38, 14, 3, "Ignition"),
        ("PART-VLV-TR414", "Tire Valve TR414", 0.25, 1, 200, 40, "Accessories"),
        ("PART-TPMS-KIT", "TPMS Rubber Valve Kit", 3.8, 8, 30, 8, "Accessories"),
    ]
    consumables = [
        ("CONS-OIL-5W30", "Engine Oil 5W-30 Full Synthetic 4L", 19.5, 30, 45, 8, "Engine oil"),
        ("CONS-OIL-10W40", "Engine Oil 10W-40 Semi Synthetic 4L", 13, 21, 50, 10, "Engine oil"),
        ("CONS-OIL-0W20", "Engine Oil 0W-20 Full Synthetic 4L", 22.5, 34, 30, 6, "Engine oil"),
        ("CONS-ATF-WS", "ATF WS 1L", 5.8, 9.5, 30, 6, "Fluids"),
        ("CONS-COOLANT", "Coolant Pre-mixed 4L", 4.2, 8, 28, 5, "Fluids"),
        ("CONS-BRK-DOT4", "Brake Fluid DOT4 500ml", 3.4, 7, 22, 5, "Fluids"),
        ("CONS-PATCH", "Tire Patch (radial)", 0.35, 2, 200, 30, "Workshop"),
        ("CONS-WEIGHT", "Wheel Weight Strip 60g", 0.5, 1.5, 120, 30, "Workshop"),
    ]

    prod = {}   # sku -> {id, sell, buy, name}
    stock = {}  # sku -> locally tracked available quantity
    racks = iter([f"{r}-{n:02d}" for r in "ABC" for n in range(1, 16)])

    for sku, name, buy, sell, opening, alert, size, brand, model, ttype in tires:
        body = {"type": "tire", "sku": sku, "name": name,
                "barcode": f"885{random.randint(10**9, 10**10 - 1)}",
                "buy_price": buy, "sell_price": sell, "stock_quantity": opening,
                "min_stock_alert": alert, "unit": "piece", "location": next(racks),
                "tire_size": size, "tire_brand": brand, "tire_model": model, "tire_type": ttype,
                "category": {"passenger": "Passenger tire", "suv": "SUV tire", "truck": "Pickup / 4x4 tire"}[ttype]}
        r = api("POST", "/products", body, token)
        prod[sku] = {"id": r["data"]["id"], "sell": sell, "buy": buy, "name": name}
        stock[sku] = opening
    for sku, name, buy, sell, opening, alert, cat in parts + consumables:
        ptype = "part" if sku.startswith("PART") else "consumable"
        body = {"type": ptype, "sku": sku, "name": name,
                "barcode": f"885{random.randint(10**9, 10**10 - 1)}",
                "buy_price": buy, "sell_price": sell, "stock_quantity": opening,
                "min_stock_alert": alert, "unit": "piece", "location": next(racks), "category": cat}
        r = api("POST", "/products", body, token)
        prod[sku] = {"id": r["data"]["id"], "sell": sell, "buy": buy, "name": name}
        stock[sku] = opening
    print(f"products: {len(prod)}")

    # Bulk oil: a 208 L drum sold retail by the liter. Two drums received, the
    # open one drawn down so the barrel gauge shows a low active drum + 1 full
    # spare behind it.
    r = api("POST", "/products", {
        "type": "consumable", "sku": "OIL-BULK-1040", "name": "Engine Oil 10W-40 (bulk, per L)",
        "category": "Oil", "buy_price": 1.92, "sell_price": 4.50, "stock_quantity": 0,
        "min_stock_alert": 25, "unit": "liter", "is_oil_product": True, "is_bulk": True,
    }, token)
    bulk_id = r["data"]["id"]
    api("POST", f"/products/{bulk_id}/receive", {"quantity": 208, "unit_cost": 1.90, "notes": "CamboLub drum"}, token)
    api("POST", f"/products/{bulk_id}/receive", {"quantity": 208, "unit_cost": 1.92, "notes": "CamboLub drum"}, token)
    api("POST", f"/products/{bulk_id}/adjust", {"quantity_change": -174, "reason": "bulk oil dispensed at counter"}, token)
    prod["OIL-BULK-1040"] = {"id": bulk_id, "sell": 4.50, "buy": 1.92, "name": "Engine Oil 10W-40 (bulk, per L)"}

    # Backdate product creation + opening batches to 120–400 days ago.
    for sku, p in prod.items():
        t = ts(random.randint(120, 400))
        bd(f"UPDATE products SET created_at='{t}', updated_at='{t}' WHERE id={p['id']}")
        bd(f"UPDATE batches SET received_at='{t}' WHERE product_id={p['id']} AND supplier='Opening stock'")
        bd(f"UPDATE stock_movements SET created_at='{t}' WHERE product_id={p['id']} AND reason='opening'")

    # ------------------------------------------------------------------ customers
    people = [
        ("Sopheak Chan", [("Toyota", "Camry", 2009), ("Toyota", "Vios", 2019)]),
        ("Dara Kim", [("Lexus", "RX330", 2005)]),
        ("Sreymom Pov", [("Toyota", "Prius", 2012)]),
        ("Vannak Heng", [("Toyota", "Hilux", 2018)]),
        ("Chenda Ly", [("Toyota", "Corolla", 2011)]),
        ("Bopha Sorn", [("Honda", "CR-V", 2015)]),
        ("Piseth Nguon", [("Toyota", "Highlander", 2013)]),
        ("Kunthea Mao", [("Kia", "Morning", 2014)]),
        ("Rathana Keo", [("Ford", "Ranger", 2019)]),
        ("Sokha Lim", [("Lexus", "RX350", 2010)]),
        ("Veasna Chhorn", [("Toyota", "Land Cruiser Prado", 2016)]),
        ("Srey Leak Tan", [("Hyundai", "Tucson", 2017)]),
        ("Makara Sam", [("Toyota", "Camry", 2013)]),
        ("Phalla Ouk", [("Honda", "Fit", 2014)]),
        ("Nita Hor", [("Toyota", "Yaris", 2020)]),
        ("Samnang Yim", [("Mitsubishi", "Triton", 2018)]),
        ("Thida Prak", [("Toyota", "Prius", 2010)]),
        ("Sovann Chea", [("Toyota", "Alphard", 2015)]),
        ("Angkor Express Logistics", [("Hyundai", "Porter", 2017), ("Toyota", "Hilux", 2020)]),
        ("PP Green Taxi Co.", [("Toyota", "Prius", 2011), ("Toyota", "Prius", 2013)]),
    ]
    customers = []  # (customer_id, [vehicle_ids], name)
    for name, vehicles in people:
        phone = f"0{random.choice(['12', '17', '77', '78', '10', '96'])} {random.randint(200, 999)} {random.randint(100, 999)}"
        r = api("POST", "/customers", {"name": name, "phone": phone}, token)
        cid = r["data"]["id"]
        vids = []
        for make, model, year in vehicles:
            plate = f"2A{random.choice('ABCDEFHKV')}-{random.randint(1000, 9999)}"
            vr = api("POST", f"/customers/{cid}/vehicles",
                     {"plate_number": plate, "make": make, "model": model, "year": year}, token)
            vids.append(vr["data"]["id"])
        customers.append((cid, vids, name))
        t = ts(random.randint(95, 400))
        bd(f"UPDATE customers SET created_at='{t}', updated_at='{t}' WHERE id={cid}")
        bd(f"UPDATE vehicles SET created_at='{t}' WHERE customer_id={cid}")
    regulars = customers[:10]
    companies = customers[-2:]
    print(f"customers: {len(customers)}")

    # ------------------------------------------------------------------ purchasing history
    # PO 1: tire restock 40 days ago, received in full, paid on delivery.
    po1 = api("POST", "/purchase-orders", {"supplier_id": suppliers["Sokha Tire Import & Trading"],
                                           "notes": "Monthly tire restock"}, token)["data"]
    for sku, qty in [("TIRE-KEN-1856515", 16), ("TIRE-WES-1956515", 16),
                     ("TIRE-HAN-2156016", 12), ("TIRE-MAX-2256517", 12), ("TIRE-BRI-2656517", 12)]:
        api("POST", f"/purchase-orders/{po1['id']}/items",
            {"product_id": prod[sku]["id"], "quantity_ordered": qty, "unit_cost": prod[sku]["buy"]}, token)
        stock[sku] += qty
    api("POST", f"/purchase-orders/{po1['id']}/place", None, token)
    api("POST", f"/purchase-orders/{po1['id']}/receive", {"paid": True}, token)
    t_po1 = ts(40, 10)
    bd(f"UPDATE purchase_orders SET created_at='{ts(41, 15)}', ordered_at='{ts(41, 15)}', "
       f"received_at='{t_po1}', updated_at='{t_po1}' WHERE id={po1['id']}")
    bd(f"UPDATE batches SET received_at='{t_po1}' WHERE notes='PO {po1['po_number']}'")
    bd(f"UPDATE stock_movements SET created_at='{t_po1}' WHERE reference_type='purchase_order' AND reference_id={po1['id']}")

    # Direct oil restock 25 days ago, on credit (accounts payable), then half-paid.
    oil_note = "Monthly oil restock — June"
    for sku, qty in [("CONS-OIL-10W40", 30), ("CONS-OIL-5W30", 24)]:
        api("POST", f"/products/{prod[sku]['id']}/receive",
            {"quantity": qty, "unit_cost": prod[sku]["buy"], "supplier_id": suppliers["CamboLub Distribution"],
             "paid": False, "notes": oil_note}, token)
        stock[sku] += qty
    api("POST", f"/suppliers/{suppliers['CamboLub Distribution']}/pay", {"amount": 300}, token)
    t_oil = ts(25, 9)
    bd(f"UPDATE batches SET received_at='{t_oil}' WHERE notes='{oil_note}'")
    bd(f"UPDATE stock_movements SET created_at='{t_oil}' WHERE batch_id IN "
       f"(SELECT id FROM batches WHERE notes='{oil_note}') AND reason='received'")

    # PO 2: parts order placed 12 days ago, still awaiting delivery.
    po2 = api("POST", "/purchase-orders", {"supplier_id": suppliers["Mekong Auto Parts Co., Ltd."],
                                           "notes": "Brake pads + filters restock"}, token)["data"]
    for sku, qty in [("PART-BRK-CAMRY", 8), ("PART-FIL-TOY", 30), ("PART-BAT-NS60L", 4)]:
        api("POST", f"/purchase-orders/{po2['id']}/items",
            {"product_id": prod[sku]["id"], "quantity_ordered": qty, "unit_cost": prod[sku]["buy"]}, token)
    api("POST", f"/purchase-orders/{po2['id']}/place", None, token)
    t_po2 = ts(12, 11)
    bd(f"UPDATE purchase_orders SET created_at='{t_po2}', ordered_at='{t_po2}', updated_at='{t_po2}' WHERE id={po2['id']}")
    print("purchasing: PO received, PO pending, oil receipt on credit")

    # ------------------------------------------------------------------ historical tickets
    tire_pool = (["TIRE-KEN-1856515", "TIRE-WES-1956515", "TIRE-MAX-1756514", "TIRE-HAN-2156016",
                  "TIRE-MAX-2256517", "TIRE-BRI-2656517", "TIRE-MAX-2656517"] * 3 +
                 ["TIRE-MIC-1856515", "TIRE-BRI-1956515", "TIRE-MIC-2156016", "TIRE-DUN-2356018",
                  "TIRE-MIC-2256517", "TIRE-DUN-2656018", "TIRE-GOO-2055516", "TIRE-YOK-2155517",
                  "TIRE-DUN-2056515", "TIRE-TOY-2856018", "TIRE-MIC-2454518"])
    oils = ["CONS-OIL-5W30", "CONS-OIL-10W40", "CONS-OIL-0W20"]

    def line(sku, qty):
        p = prod[sku]
        return {"product_id": p["id"], "item_type": "product", "description": p["name"],
                "quantity": qty, "unit_price_usd": p["sell"]}

    def labor(desc, qty, price):
        return {"item_type": "labor", "description": desc, "quantity": qty, "unit_price_usd": price}

    def pick_tire(need):
        cands = [s for s in tire_pool if stock[s] >= need + 5]
        return random.choice(cands) if cands else None

    def build_ticket():
        roll = random.random()
        items = []
        if roll < 0.42:  # tire replacement
            qty = random.choice([2, 2, 4, 4, 4, 1])
            sku = pick_tire(qty)
            if sku:
                stock[sku] -= qty
                items.append(line(sku, qty))
                items.append(labor("Tire installation & balancing", qty, 2.5))
                if random.random() < 0.4:
                    items.append(labor("Wheel alignment (3D)", 1, 12))
        elif roll < 0.62:  # oil change
            oil = random.choice(oils)
            filt = random.choice(["PART-FIL-TOY", "PART-FIL-TOY", "PART-FIL-HON"])
            if stock[oil] > 4 and stock[filt] > 4:
                stock[oil] -= 1
                stock[filt] -= 1
                items = [line(oil, 1), line(filt, 1), labor("Oil change service", 1, 3)]
        elif roll < 0.72:  # puncture repair
            stock["CONS-PATCH"] -= 1
            items = [line("CONS-PATCH", 1), labor("Tire puncture repair", 1, 3)]
        elif roll < 0.80:  # battery
            bat = random.choice(["PART-BAT-NS60L", "PART-BAT-N70"])
            if stock[bat] > 2:
                stock[bat] -= 1
                items = [line(bat, 1), labor("Battery installation", 1, 2)]
        elif roll < 0.88:  # brake job
            pads = random.choice(["PART-BRK-CAMRY", "PART-BRK-CRV"])
            if stock[pads] > 3:
                stock[pads] -= 1
                items = [line(pads, 1), labor("Front brake service", 1, 15)]
                if stock["CONS-BRK-DOT4"] > 3:
                    stock["CONS-BRK-DOT4"] -= 1
                    items.append(line("CONS-BRK-DOT4", 1))
        else:  # misc accessory / fluids
            sku = random.choice(["PART-WIP-2418", "CONS-COOLANT", "CONS-ATF-WS", "PART-TPMS-KIT", "PART-SPK-IRID"])
            if stock[sku] > 3:
                q = random.choice([1, 1, 2])
                stock[sku] -= q
                items = [line(sku, q)]
                if sku == "CONS-ATF-WS":
                    items.append(labor("ATF drain & refill", 1, 8))
        return items

    def pay_invoice(inv_id, total, style):
        if style == "unpaid":
            return
        amount = round(total / 2, 2) if style == "partial" else total
        body = {"amount": amount, "method": "cash"}
        if style == "khr":
            body.update({"currency": "KHR", "exchange_rate": RATE,
                         "tendered_amount": ((int(amount * RATE) + 99) // 100) * 100})
        elif style == "transfer":
            body["method"] = "transfer"
        api("POST", f"/invoices/{inv_id}/payments", body, token)

    def pay_style(cust_id):
        r = random.random()
        if cust_id is None:  # walk-ins always settle before leaving
            return "cash" if r < 0.66 else ("khr" if r < 0.90 else "transfer")
        if r < 0.52:
            return "cash"
        if r < 0.70:
            return "khr"
        if r < 0.80:
            return "transfer"
        if r < 0.91:
            return "partial"
        return "unpaid"

    offsets = sorted(random.choices(range(2, 90), k=148), reverse=True) + [1, 1]
    made_invoices = 0
    made_jobs = 0
    for d in offsets:
        items = build_ticket()
        if not items:
            continue
        cust_id = vehicle_id = None
        if random.random() < 0.58:
            cust_id, vids, _ = random.choice(regulars if random.random() < 0.6 else customers[:18])
            vehicle_id = random.choice(vids) if vids else None
        t_inv = ts(d)
        as_job = random.random() < 0.32 and cust_id is not None
        if as_job:
            job_items = [{k if k != "unit_price_usd" else "unit_price": v for k, v in it.items()} for it in items]
            job = api("POST", "/service-jobs", {
                "customer_id": cust_id, "vehicle_id": vehicle_id,
                "description": items[-1]["description"] if len(items) == 1 else items[0]["description"],
                "assigned_to": random.choice(techs), "items": job_items,
            }, token)["data"]
            api("PUT", f"/service-jobs/{job['id']}",
                {"status": "in_progress", "actual_hours": round(random.uniform(0.5, 3), 1)}, token)
            api("POST", f"/service-jobs/{job['id']}/complete", None, token)
            inv = api("POST", f"/service-jobs/{job['id']}/invoice", {"exchange_rate": RATE}, token)["data"]
            backdate_job(job["id"], ts(d, 8), t_inv)
            made_jobs += 1
        else:
            inv = api("POST", "/invoices", {"customer_id": cust_id, "vehicle_id": vehicle_id,
                                            "items": items, "exchange_rate": RATE}, token)["data"]
        pay_invoice(inv["id"], inv["total_usd"], pay_style(cust_id))
        backdate_invoice(inv["id"], t_inv)
        made_invoices += 1
    print(f"historical tickets: {made_invoices} invoices ({made_jobs} via jobs)")

    # Company fleet invoices left owing (receivables aging story).
    for (cid, vids, _), d, style in [(companies[0], 38, "unpaid"), (companies[1], 17, "partial")]:
        sku = pick_tire(4) or "TIRE-WES-1956515"
        stock[sku] -= 4
        inv = api("POST", "/invoices", {
            "customer_id": cid, "vehicle_id": vids[0],
            "items": [line(sku, 4), labor("Tire installation & balancing", 4, 2.5)],
            "exchange_rate": RATE, "notes": "Fleet account — payment on invoice",
        }, token)["data"]
        pay_invoice(inv["id"], inv["total_usd"], style)
        backdate_invoice(inv["id"], ts(d))

    # Low-stock stories: two slow movers sold down under their alert level.
    for sku, qty, d in [("TIRE-KEN-1656513", 4, 4), ("TIRE-CON-2355518", 4, 3)]:
        stock[sku] -= qty
        inv = api("POST", "/invoices", {"items": [line(sku, qty), labor("Tire installation & balancing", qty, 2.5)],
                                        "exchange_rate": RATE}, token)["data"]
        pay_invoice(inv["id"], inv["total_usd"], "cash")
        backdate_invoice(inv["id"], ts(d))

    # Return story: 2 tires sold 6 days ago, 1 came back the next day.
    ret_cust = customers[4]  # Chenda Ly
    sku = "TIRE-MIC-1856515"
    stock[sku] -= 2
    inv = api("POST", "/invoices", {"customer_id": ret_cust[0], "vehicle_id": ret_cust[1][0],
                                    "items": [line(sku, 2), labor("Tire installation & balancing", 2, 2.5)],
                                    "exchange_rate": RATE}, token)["data"]
    pay_invoice(inv["id"], inv["total_usd"], "cash")
    backdate_invoice(inv["id"], ts(6))
    detail = api("GET", f"/invoices/{inv['id']}", None, token)["data"]
    item_id = next(i["id"] for i in detail["items"] if i.get("product_id") == prod[sku]["id"])
    ret = api("POST", "/returns", {"invoice_id": inv["id"], "refund_method": "cash",
                                   "reason": "Wrong size — customer exchanged",
                                   "items": [{"invoice_item_id": item_id, "quantity": 1}]}, token)["data"]
    stock[sku] += 1
    t_ret = ts(5, 10)
    bd(f"UPDATE returns SET created_at='{t_ret}' WHERE id={ret['id']}")
    bd(f"UPDATE stock_movements SET created_at='{t_ret}' WHERE reference_type='return' AND reference_id={ret['id']}")
    bd(f"UPDATE batches SET received_at='{t_ret}' WHERE supplier='Customer return'")
    print("return + fleet AR + low-stock stories done")

    # Deposit held for a fleet account.
    dep = api("POST", "/deposits", {"customer_id": companies[0][0], "amount": 100,
                                    "note": "Advance for fleet tire order"}, token)["data"]
    bd(f"UPDATE deposits SET created_at='{ts(15, 14)}' WHERE id={dep['id']}")

    # Stocktake 20 days ago: small real-world variances.
    st = api("POST", "/stocktakes", {"notes": "Monthly accessories count"}, token)["data"]
    counts = []
    for sku, delta in [("PART-VLV-TR414", -3), ("PART-WIP-2418", 1), ("CONS-COOLANT", 0)]:
        p = api("GET", f"/products/{prod[sku]['id']}", None, token)["data"]
        it = api("POST", f"/stocktakes/{st['id']}/items", {"product_id": prod[sku]["id"]}, token)["data"]
        counts.append((it["id"], p["stock_quantity"] + delta))
        stock[sku] += delta
    for item_id, counted in counts:
        api("PUT", f"/stocktakes/items/{item_id}", {"counted_qty": counted}, token)
    api("POST", f"/stocktakes/{st['id']}/finalize", None, token)
    t_st = ts(20, 17)
    bd(f"UPDATE stocktakes SET created_at='{ts(20, 16)}', completed_at='{t_st}', updated_at='{t_st}' WHERE id={st['id']}")
    bd(f"UPDATE stocktake_items SET counted_at='{ts(20, 16)}' WHERE stocktake_id={st['id']}")
    bd(f"UPDATE stock_movements SET created_at='{t_st}' WHERE reference_type='stocktake' AND reference_id={st['id']}")
    bd(f"UPDATE batches SET received_at='{t_st}' WHERE supplier='Stocktake'")

    # Operating expenses over the last three months (spent_at is honored directly).
    month_firsts = []
    d = TODAY.replace(day=1)
    for _ in range(3):
        month_firsts.append(d)
        d = (d - timedelta(days=1)).replace(day=1)
    for m in month_firsts:
        api("POST", "/expenses", {"category": "Rent", "amount_usd": 600, "spent_at": m.isoformat()}, token)
        api("POST", "/expenses", {"category": "Utilities", "amount_usd": round(random.uniform(130, 175), 2),
                                  "description": "EDC electricity", "spent_at": (m + timedelta(days=4)).isoformat()}, token)
        api("POST", "/expenses", {"category": "Utilities", "amount_usd": 30,
                                  "description": "Internet", "spent_at": (m + timedelta(days=2)).isoformat()}, token)
    api("POST", "/expenses", {"category": "Supplies", "amount_usd": 42.5,
                              "description": "Valve stems, patches, shop rags",
                              "spent_at": (TODAY - timedelta(days=22)).isoformat()}, token)
    api("POST", "/expenses", {"category": "Maintenance", "amount_usd": 85,
                              "description": "Compressor service", "spent_at": (TODAY - timedelta(days=47)).isoformat()}, token)
    print("expenses, deposit, stocktake done")

    # ------------------------------------------------------------------ live "today" state
    def job_items(items):
        """Invoice-shaped lines -> job-shaped lines (unit_price_usd -> unit_price)."""
        return [{("unit_price" if k == "unit_price_usd" else k): v for k, v in it.items()} for it in items]

    # Active jobs on the floor (these keep today's timestamps + reserve stock).
    j = api("POST", "/service-jobs", {
        "customer_id": customers[9][0], "vehicle_id": customers[9][1][0],
        "description": "Replace 4 tires + alignment", "assigned_to": techs[0],
        "items": job_items([line("TIRE-DUN-2356018", 4),
                            labor("Tire installation & balancing", 4, 2.5),
                            labor("Wheel alignment (3D)", 1, 12)]),
    }, token)["data"]
    api("PUT", f"/service-jobs/{j['id']}", {"status": "in_progress"}, token)

    j = api("POST", "/service-jobs", {
        "customer_id": customers[12][0], "vehicle_id": customers[12][1][0],
        "description": "Front brake pads replacement", "assigned_to": techs[1],
        "items": job_items([line("PART-BRK-CAMRY", 1), labor("Front brake service", 1, 15)]),
    }, token)["data"]
    api("PUT", f"/service-jobs/{j['id']}", {"status": "in_progress"}, token)

    tomorrow = (TODAY + timedelta(days=1)).isoformat()
    api("POST", "/service-jobs", {
        "customer_id": customers[6][0], "vehicle_id": customers[6][1][0],
        "description": "4 new tires — customer confirmed by phone", "assigned_to": techs[2],
        "scheduled_at": f"{tomorrow}T09:00:00+07:00",
        "items": job_items([line("TIRE-MAX-2256517", 4),
                            labor("Tire installation & balancing", 4, 2.5)]),
    }, token)
    api("POST", "/service-jobs", {
        "customer_id": customers[2][0], "vehicle_id": customers[2][1][0],
        "description": "Oil change + multi-point check",
        "scheduled_at": f"{(TODAY + timedelta(days=4)).isoformat()}T14:30:00+07:00",
    }, token)

    # Note: line() already decremented nothing for job items above; adjust tracker.
    stock["TIRE-DUN-2356018"] -= 4
    stock["PART-BRK-CAMRY"] -= 1
    stock["TIRE-MAX-2256517"] -= 4

    # Open today's drawer, then ring up this morning's sales.
    api("POST", "/cash-shifts/open", {"opening_float": 50}, token)
    inv = api("POST", "/invoices", {"items": [line("CONS-PATCH", 1), labor("Tire puncture repair", 1, 3)],
                                    "exchange_rate": RATE}, token)["data"]
    pay_invoice(inv["id"], inv["total_usd"], "khr")
    oil_cust = customers[13]
    inv = api("POST", "/invoices", {"customer_id": oil_cust[0], "vehicle_id": oil_cust[1][0],
                                    "items": [line("CONS-OIL-0W20", 1), line("PART-FIL-HON", 1),
                                              labor("Oil change service", 1, 3)],
                                    "exchange_rate": RATE}, token)["data"]
    pay_invoice(inv["id"], inv["total_usd"], "cash")
    print("live state: 2 jobs in progress, 2 scheduled, drawer open with 2 sales")

    # Yesterday's closed drawer, computed from yesterday's (backdated) cash takings.
    y = (TODAY - timedelta(days=1)).isoformat()
    bd(f"""INSERT INTO cash_shifts (branch_id, opened_by, closed_by, opening_float, cash_sales,
       expected_amount, closing_amount, over_short, opened_at, closed_at, status)
SELECT 1, 1, 1, 50.00, t.s, 50.00 + t.s, 50.00 + t.s - 2.00, -2.00,
       '{y} 07:45:00+07', '{y} 17:40:00+07', 'closed'
FROM (SELECT COALESCE(SUM(p.amount), 0) AS s FROM payments p
      WHERE p.method = 'cash'
        AND p.created_at >= '{y} 00:00:00+07' AND p.created_at < '{TODAY.isoformat()} 00:00:00+07') t""")

    BACKDATE_SQL.append("COMMIT;")
    with open(out_path, "w") as f:
        f.write("\n".join(BACKDATE_SQL) + "\n")
    print(f"wrote {out_path} ({len(BACKDATE_SQL)} statements) — apply it with psql now")


if __name__ == "__main__":
    main()
